version: '3.8'
services:
  app:
    container_name: thesis_49371_backend
    build: ./backend
    volumes:
      - ./backend/app:/backend/app
    ports:
      - ${APP_PORT}:80
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@thesis_49371_db:${DB_PORT}/${DB_DATA}
    depends_on:
      - db
    restart: always
  client:
    container_name: thesis_49371_frontend
    build: ./frontend
    ports:
      - ${CLIENT_PORT}:80
    environment:
      - POLLUTION_API_URL=http://thesis_49371_backend:${APP_PORT}
  db:
    container_name: thesis_49371_db
    image: postgres:16.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATA}
    volumes:
      - .db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    restart: always
